//<![CDATA[
jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(d,b,a,c,e){return jQuery.easing[jQuery.easing.def](d,b,a,c,e)},easeInQuad:function(d,b,a,c,e){return c*(b/=e)*b+a},easeOutQuad:function(d,b,a,c,e){return-c*(b/=e)*(b-2)+a},easeInOutQuad:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b+a:-c/2*(--b*(b-2)-1)+a},easeInCubic:function(d,b,a,c,e){return c*(b/=e)*b*b+a},easeOutCubic:function(d,b,a,c,e){return c*((b=b/e-1)*b*b+1)+a},easeInOutCubic:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b+a:
c/2*((b-=2)*b*b+2)+a},easeInQuart:function(d,b,a,c,e){return c*(b/=e)*b*b*b+a},easeOutQuart:function(d,b,a,c,e){return-c*((b=b/e-1)*b*b*b-1)+a},easeInOutQuart:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b*b+a:-c/2*((b-=2)*b*b*b-2)+a},easeInQuint:function(d,b,a,c,e){return c*(b/=e)*b*b*b*b+a},easeOutQuint:function(d,b,a,c,e){return c*((b=b/e-1)*b*b*b*b+1)+a},easeInOutQuint:function(d,b,a,c,e){return 1>(b/=e/2)?c/2*b*b*b*b*b+a:c/2*((b-=2)*b*b*b*b+2)+a},easeInSine:function(d,b,a,c,e){return-c*Math.cos(b/
e*(Math.PI/2))+c+a},easeOutSine:function(d,b,a,c,e){return c*Math.sin(b/e*(Math.PI/2))+a},easeInOutSine:function(d,b,a,c,e){return-c/2*(Math.cos(Math.PI*b/e)-1)+a},easeInExpo:function(d,b,a,c,e){return 0==b?a:c*Math.pow(2,10*(b/e-1))+a},easeOutExpo:function(d,b,a,c,e){return b==e?a+c:c*(1-Math.pow(2,-10*b/e))+a},easeInOutExpo:function(d,b,a,c,e){return 0==b?a:b==e?a+c:1>(b/=e/2)?c/2*Math.pow(2,10*(b-1))+a:c/2*(2-Math.pow(2,-10*--b))+a},easeInCirc:function(d,b,a,c,e){return-c*(Math.sqrt(1-(b/=e)*b)-
1)+a},easeOutCirc:function(d,b,a,c,e){return c*Math.sqrt(1-(b=b/e-1)*b)+a},easeInOutCirc:function(d,b,a,c,e){return 1>(b/=e/2)?-c/2*(Math.sqrt(1-b*b)-1)+a:c/2*(Math.sqrt(1-(b-=2)*b)+1)+a},easeInElastic:function(d,b,a,c,e){d=0;var f=c;if(0==b)return a;if(1==(b/=e))return a+c;(d||(d=.3*e),f<Math.abs(c))?(f=c,c=d/4):c=d/(2*Math.PI)*Math.asin(c/f);return-f*Math.pow(2,10*--b)*Math.sin(2*(b*e-c)*Math.PI/d)+a},easeOutElastic:function(d,b,a,c,e){var f=0,g=c;if(0==b)return a;if(1==(b/=e))return a+c;(f||(f=
.3*e),g<Math.abs(c))?(g=c,d=f/4):d=f/(2*Math.PI)*Math.asin(c/g);return g*Math.pow(2,-10*b)*Math.sin(2*(b*e-d)*Math.PI/f)+c+a},easeInOutElastic:function(d,b,a,c,e){var f=0,g=c;if(0==b)return a;if(2==(b/=e/2))return a+c;(f||(f=.3*e*1.5),g<Math.abs(c))?(g=c,d=f/4):d=f/(2*Math.PI)*Math.asin(c/g);return 1>b?g*Math.pow(2,10*--b)*Math.sin(2*(b*e-d)*Math.PI/f)*-.5+a:g*Math.pow(2,-10*--b)*Math.sin(2*(b*e-d)*Math.PI/f)*.5+c+a},easeInBack:function(d,b,a,c,e,f){return void 0==f&&(f=1.70158),c*(b/=e)*b*((f+1)*
b-f)+a},easeOutBack:function(d,b,a,c,e,f){return void 0==f&&(f=1.70158),c*((b=b/e-1)*b*((f+1)*b+f)+1)+a},easeInOutBack:function(d,b,a,c,e,f){return void 0==f&&(f=1.70158),1>(b/=e/2)?c/2*b*b*((1+(f*=1.525))*b-f)+a:c/2*((b-=2)*b*((1+(f*=1.525))*b+f)+2)+a},easeInBounce:function(d,b,a,c,e){return c-jQuery.easing.easeOutBounce(d,e-b,0,c,e)+a},easeOutBounce:function(d,b,a,c,e){return(b/=e)<1/2.75?7.5625*c*b*b+a:b<2/2.75?c*(7.5625*(b-=1.5/2.75)*b+.75)+a:b<2.5/2.75?c*(7.5625*(b-=2.25/2.75)*b+.9375)+a:c*(7.5625*
(b-=2.625/2.75)*b+.984375)+a},easeInOutBounce:function(d,b,a,c,e){return b<e/2?.5*jQuery.easing.easeInBounce(d,2*b,0,c,e)+a:.5*jQuery.easing.easeOutBounce(d,2*b-e,0,c,e)+.5*c+a}});var searchFormConfig={summaryPost:!0,resultThumbnail:!0,fallbackThumb:"http://1.bp.blogspot.com/-41xX9MKBr-w/U1Tt0T8gNRI/AAAAAAAABZw/SocPS0qeq1k/s50-c/Noim.png",thumbSize:50,summaryLength:100};
!function(d){var b=d("#ajax-search-form"),a=b.find(":text");config=searchFormConfig;b.append('<div id="search-result"></div>');var c=d("#search-result");b.on("submit",function(){var b=a.val();return c.slideDown(500,"easeOutBounce").html("Loading..."),d.ajax({url:"//codexreloadedgames.blogspot.com//feeds/posts/summary?alt=json-in-script&q="+b+"&max-results=9999",type:"get",dataType:"jsonp",success:function(a){var e,d,f;a=a.feed.entry;if(void 0!==a){var l="<h4>Search results for keyword &quot;"+b+"&quot;</h4>";
l+='<a class="close" href="/">&times;</a><ul>';for(var m=0;m<a.length;m++){for(var h=new RegExp(b,"ig"),n=a[m].title.$t.replace(h,"<mark>"+b+"</mark>"),r=0;r<a[m].link.length;r++)"alternate"==a[m].link[r].rel&&(f=a[m].link[r].href);!0===config.summaryPost&&(e="content"in a[m]?a[m].content.$t:"summary"in a[m]?a[m].summary.$t:"");!0===config.resultThumbnail&&(d="media$thumbnail"in a[m]?a[m].media$thumbnail.url.replace(/\/s[0-9]+\-c/g,"/s"+config.thumbSize+"-c"):config.fallbackThumb);(e=e.replace(/<\S[^>]*>/g,
"")).length>config.summaryLength&&(e=e.substring(0,config.summaryLength)+"...");l+='<li><a href="'+f+'" target="_blank"><span><img src="'+d+'" alt="" /></span><h5>'+n+"</h5></a><p>"+(e=e.replace(h,"<mark>"+b+"</mark>"))+"</p></li>"}c.html(l+"</ul>")}else c.html('<a class="close" href="/">&times;</a><strong>No result!</strong>')},error:function(){c.html('<a class="close" href="/">&times;</a><strong>Error loading feed.</strong>')}}),!1});b.on("click",".close",function(){return c.slideUp(500,"easeInExpo"),
!1})}(jQuery);/*
 lazysizes - v4.1.2 */
!function(d,b){var a=b(d,d.document);d.lazySizes=a;"object"==typeof module&&module.exports&&(module.exports=a)}(window,function(d,b){if(b.getElementsByClassName){var a,c,e=b.documentElement,f=d.Date,g=d.HTMLPictureElement,k=d.addEventListener,p=d.setTimeout,l=d.requestAnimationFrame||p,m=d.requestIdleCallback,h=/^picture$/i,n=["load","error","lazyincluded","_lazyloaded"],r={},E=Array.prototype.forEach,F=function(a,c){return r[c]||(r[c]=new RegExp("(\\s|^)"+c+"(\\s|$)")),r[c].test(a.getAttribute("class")||
"")&&r[c]},B=function(a,c){F(a,c)||a.setAttribute("class",(a.getAttribute("class")||"").trim()+" "+c)},G=function(a,c){var b;(b=F(a,c))&&a.setAttribute("class",(a.getAttribute("class")||"").replace(b," "))},M=function(a,c,b){var e=b?"addEventListener":"removeEventListener";b&&M(a,c);n.forEach(function(b){a[e](b,c)})},K=function(c,e,d,f,g){var h=b.createEvent("CustomEvent");return d||(d={}),d.instance=a,h.initCustomEvent(e,!f,!g,d),c.dispatchEvent(h),h},u=function(a,b){var e;!g&&(e=d.picturefill||
c.pf)?(b&&b.src&&!a.getAttribute("srcset")&&a.setAttribute("srcset",b.src),e({reevaluate:!0,elements:[a]})):b&&b.src&&(a.src=b.src)},w=function(a,c){return(getComputedStyle(a,null)||{})[c]},N=function(a,b,e){for(e=e||a.offsetWidth;e<c.minSize&&b&&!a._lazysizesWidth;)e=b.offsetWidth,b=b.parentNode;return e},L=function(){var a,c,e=[],d=[],f=e,g=function(){var b=f;f=e.length?d:e;a=!0;for(c=!1;b.length;)b.shift()();a=!1},h=function(e,d){a&&!d?e.apply(this,arguments):(f.push(e),c||(c=!0,(b.hidden?p:l)(g)))};
return h._lsFlush=g,h}(),z=function(a,c){return c?function(){L(a)}:function(){var c=this,b=arguments;L(function(){a.apply(c,b)})}},V=function(a){var b,e=0,d=c.throttleDelay,g=c.ricTimeout,h=function(){b=!1;e=f.now();a()},k=m&&49<g?function(){m(h,{timeout:g});g!==c.ricTimeout&&(g=c.ricTimeout)}:z(function(){p(h)},!0);return function(a){var c;(a=!0===a)&&(g=33);b||(b=!0,c=d-(f.now()-e),0>c&&(c=0),a||9>c?k():p(k,c))}},R=function(a){var c,b,e=function(){c=null;a()},d=function(){var a=f.now()-b;99>a?p(d,
99-a):(m||e)(e)};return function(){b=f.now();c||(c=p(d,99))}};!function(){var a,b={lazyClass:"lazyload",loadedClass:"lazyloaded",loadingClass:"lazyloading",preloadClass:"lazypreload",errorClass:"lazyerror",autosizesClass:"lazyautosizes",srcAttr:"data-src",srcsetAttr:"data-srcset",sizesAttr:"data-sizes",minSize:40,customMedia:{},init:!0,expFactor:1.5,hFac:.8,loadMode:2,loadHidden:!0,ricTimeout:0,throttleDelay:125};c=d.lazySizesConfig||d.lazysizesConfig||{};for(a in b)a in c||(c[a]=b[a]);d.lazySizesConfig=
c;p(function(){c.init&&v()})}();var y=function(){var g,l,m,n,H,r,Q,I,J,S,v,y,W,ca,N=/^img$/i,ha=/^iframe$/i,ia="onscroll"in d&&!/(gle|ing)bot/.test(navigator.userAgent),X=0,D=0,O=-1,Y=function(a){D--;a&&a.target&&M(a.target,Y);(!a||0>D||!a.target)&&(D=0)},da=function(){var d,f,h,k,p,m,H,q=a.elements;if((n=c.loadMode)&&8>D&&(d=q.length)){var A=0;O++;null==W&&("expand"in c||(c.expand=500<e.clientHeight&&500<e.clientWidth?500:370),y=c.expand,W=y*c.expFactor);for(W>X&&1>D&&2<O&&2<n&&!b.hidden?(X=W,O=
0):X=1<n&&1<O&&6>D?y:0;d>A;A++)if(q[A]&&!q[A]._lazyRace)if(ia){(m=q[A].getAttribute("data-expand"))&&(k=1*m)||(k=X);H!==k&&(r=innerWidth+k*ca,Q=innerHeight+k,p=-1*k,H=k);var x=q[A].getBoundingClientRect();if((x=(v=x.bottom)>=p&&(I=x.top)<=Q&&(S=x.right)>=p*ca&&(J=x.left)<=r&&(v||S||J||I)&&(c.loadHidden||"hidden"!=w(q[A],"visibility")))&&!(x=l&&3>D&&!m&&(3>n||4>O))){x=void 0;var C=q[A],u=k,t=C;C="hidden"==w(b.body,"visibility")||"hidden"!=w(C.parentNode,"visibility")&&"hidden"!=w(C,"visibility");I-=
u;v+=u;J-=u;for(S+=u;C&&(t=t.offsetParent)&&t!=b.body&&t!=e;)(C=0<(w(t,"opacity")||1))&&"visible"!=w(t,"overflow")&&(x=t.getBoundingClientRect(),C=S>x.left&&J<x.right&&v>x.top-1&&I<x.bottom+1);x=C}if(x){if(Z(q[A]),h=!0,9<D)break}else!h&&l&&!f&&4>D&&4>O&&2<n&&(g[0]||c.preloadAfterLoad)&&(g[0]||!m&&(v||S||J||I||"auto"!=q[A].getAttribute(c.sizesAttr)))&&(f=g[0]||q[A])}else Z(q[A]);f&&!h&&Z(f)}},t=V(da),fa=function(a){B(a.target,c.loadedClass);G(a.target,c.loadingClass);M(a.target,ea);K(a.target,"lazyloaded")},
ja=z(fa),ea=function(a){ja({target:a.target})},ka=function(a,c){try{a.contentWindow.location.replace(c)}catch(na){a.src=c}},la=function(a){var b,e=a.getAttribute(c.srcsetAttr);(b=c.customMedia[a.getAttribute("data-media")||a.getAttribute("media")])&&a.setAttribute("media",b);e&&a.setAttribute("srcset",e)},ma=z(function(a,b,e,d,f){var g,k,I,l,n,J;(n=K(a,"lazybeforeunveil",b)).defaultPrevented||(d&&(e?B(a,c.autosizesClass):a.setAttribute("sizes",d)),k=a.getAttribute(c.srcsetAttr),g=a.getAttribute(c.srcAttr),
f&&(I=a.parentNode,l=I&&h.test(I.nodeName||"")),J=b.firesLoad||"src"in a&&(k||g||l),n={target:a},J&&(M(a,Y,!0),clearTimeout(m),m=p(Y,2500),B(a,c.loadingClass),M(a,ea,!0)),l&&E.call(I.getElementsByTagName("source"),la),k?a.setAttribute("srcset",k):g&&!l&&(ha.test(a.nodeName)?ka(a,g):a.src=g),f&&(k||l)&&u(a,{src:g}));a._lazyRace&&delete a._lazyRace;G(a,c.lazyClass);L(function(){(!J||a.complete&&1<a.naturalWidth)&&(J?Y(n):D--,fa(n))},!0)}),Z=function(a){var b,e=N.test(a.nodeName),d=e&&(a.getAttribute(c.sizesAttr)||
a.getAttribute("sizes")),f="auto"==d;(!f&&l||!e||!a.getAttribute("src")&&!a.srcset||a.complete||F(a,c.errorClass)||!F(a,c.lazyClass))&&(b=K(a,"lazyunveilread").detail,f&&q.updateElem(a,!0,a.offsetWidth),a._lazyRace=!0,D++,ma(a,b,f,d,e))},aa=function(){if(!l){if(999>f.now()-H)return void p(aa,999);var a=R(function(){c.loadMode=3;t()});l=!0;c.loadMode=3;t();k("scroll",function(){3==c.loadMode&&(c.loadMode=2);a()},!0)}};return{_:function(){H=f.now();a.elements=b.getElementsByClassName(c.lazyClass);g=
b.getElementsByClassName(c.lazyClass+" "+c.preloadClass);ca=c.hFac;k("scroll",t,!0);k("resize",t,!0);d.MutationObserver?(new MutationObserver(t)).observe(e,{childList:!0,subtree:!0,attributes:!0}):(e.addEventListener("DOMNodeInserted",t,!0),e.addEventListener("DOMAttrModified",t,!0),setInterval(t,999));k("hashchange",t,!0);"focus mouseover click load transitionend animationend webkitAnimationEnd".split(" ").forEach(function(a){b.addEventListener(a,t,!0)});/d$|^c/.test(b.readyState)?aa():(k("load",
aa),b.addEventListener("DOMContentLoaded",t),p(aa,2E4));a.elements.length?(da(),L._lsFlush()):t()},checkElems:t,unveil:Z}}(),q=function(){var a,e=z(function(a,c,b,e){var d;if(a._lazysizesWidth=e,e+="px",a.setAttribute("sizes",e),h.test(c.nodeName||"")){c=c.getElementsByTagName("source");var f=0;for(d=c.length;d>f;f++)c[f].setAttribute("sizes",e)}b.detail.dataAttr||u(a,b.detail)}),d=function(a,c,b){var d,f=a.parentNode;f&&(b=N(a,f,b),d=K(a,"lazybeforesizes",{width:b,dataAttr:!!c}),d.defaultPrevented||
(b=d.detail.width,b&&b!==a._lazysizesWidth&&e(a,f,d,b)))},f=R(function(){var c,b=a.length;if(b)for(c=0;b>c;c++)d(a[c])});return{_:function(){a=b.getElementsByClassName(c.autosizesClass);k("resize",f)},checkElems:f,updateElem:d}}(),v=function(){v.i||(v.i=!0,q._(),y._())};return a={cfg:c,autoSizer:q,loader:y,init:v,uP:u,aC:B,rC:G,hC:F,fire:K,gW:N,rAF:L}}});/*
 Slimbox v2.05 - The ultimate lightweight Lightbox clone for jQuery (c) 2007-2013 Christophe Beyls <http://www.digitalia.be>  Modified by <aura-ilmu.com>  MIT-style license. */
(function(d){function b(){var a=h.scrollLeft(),c=h.width();d([q,P]).css("left",a+c/2);M&&d(y).css({left:a,top:h.scrollTop(),width:c,height:h.height()})}function a(a){a?d("object").add(N?"select":"embed").each(function(a,c){L[a]=[c,c.style.visibility];c.style.visibility="hidden"}):(d.each(L,function(a,c){c[0].style.visibility=c[1]}),L=[]);a=a?"bind":"unbind";h[a]("scroll resize",b);d(document)[a]("keydown",c)}function c(a){a=a.which;var c=d.inArray;return 0<=c(a,n.closeKeys)?m():0<=c(a,n.nextKeys)?
f():0<=c(a,n.previousKeys)?e():null}function e(){return g(B)}function f(){return g(G)}function g(a){0<=a&&(E=a,F=r[E][0],B=(E||(n.loop?r.length:0))-1,G=(E+1)%r.length||(n.loop?0:-1),l(),q.className="lbLoading",z=new Image,z.onload=k,z.src=F);return!1}function k(){q.className="";d(v).css({backgroundImage:"url("+F+")",visibility:"hidden",display:""});d(ba).width(z.width);d([ba,T,U]).height(z.height);d(C).html(r[E][1]||"");d(Q).html((1<r.length&&n.counterText||"").replace(/{x}/,E+1).replace(/{y}/,r.length));
0<=B&&(V.src=r[B][0]);0<=G&&(R.src=r[G][0]);u=v.offsetWidth;w=v.offsetHeight;var a=Math.max(0,K-w/2);q.offsetHeight!=w&&d(q).animate({height:w,top:a},n.resizeDuration,n.resizeEasing);q.offsetWidth!=u&&d(q).animate({width:u,marginLeft:-u/2},n.resizeDuration,n.resizeEasing);d(q).queue(function(){d(P).css({width:u,top:a+w,marginLeft:-u/2,visibility:"hidden",display:""});d(v).css({display:"none",visibility:"",opacity:""}).fadeIn(n.imageFadeDuration,p)})}function p(){0<=B&&d(T).show();0<=G&&d(U).show();
d(H).css("marginTop",-H.offsetHeight).animate({marginTop:0},n.captionAnimationDuration);P.style.visibility=""}function l(){z.onload=null;z.src=V.src=R.src=F;d([q,v,H]).stop(!0);d([T,U,v,P]).hide()}function m(){0<=E&&(l(),E=B=G=-1,d(q).hide(),d(y).stop().fadeOut(n.overlayFadeDuration,a));return!1}var h=d(window),n,r,E=-1,F,B,G,M,K,u,w,N=!window.XMLHttpRequest,L=[],z={},V=new Image,R=new Image,y,q,v,ba,T,U,P,H,C,Q;d(function(){d("body").append(d([y=d('<div id="lbOverlay" />').click(m)[0],q=d('<div id="lbCenter" />')[0],
P=d('<div id="lbBottomContainer" />')[0]]).css("display","none"));v=d('<div id="lbImage" />').appendTo(q).append(ba=d('<div style="position: relative;" />').append([])[0])[0];H=d('<div id="lbBottom" />').appendTo(q).append([C=d('<div id="lbCaption" />')[0],Q=d('<div id="lbNumber" />')[0],T=d('<a id="lbPrevLink" href="#" />').click(e)[0],U=d('<a id="lbNextLink" href="#" />').click(f)[0],d('<a id="lbCloseLink" href="#" />').click(m)[0],d('<div style="clear: both;" />')[0]])[0]});d.slimbox=function(c,
e,f){n=d.extend({loop:!1,overlayOpacity:.9,overlayFadeDuration:400,resizeDuration:400,resizeEasing:"easeOutElastic",initialWidth:250,initialHeight:250,imageFadeDuration:400,captionAnimationDuration:400,counterText:"Image {x} of {y}",closeKeys:[27,88,67],previousKeys:[37,80],nextKeys:[39,78]},f);"string"==typeof c&&(c=[[c,e]],e=0);K=h.scrollTop()+h.height()/2;u=n.initialWidth;w=n.initialHeight;d(q).css({top:Math.max(0,K-w/2),width:u,height:w,marginLeft:-u/2}).show();if(M=N||y.currentStyle&&"fixed"!=
y.currentStyle.position)y.style.position="absolute";d(y).css("opacity",n.overlayOpacity).fadeIn(n.overlayFadeDuration);b();a(1);r=c;n.loop=n.loop&&1<r.length;return g(e)};d.fn.slimbox=function(a,c,b){c=c||function(a){return[a.href,a.title]};b=b||function(){return!0};var e=this;return e.unbind("click").click(function(){var f=this,g=0,h=0,k;var l=d.grep(e,function(a,c){return b.call(f,a,c)});for(k=l.length;h<k;++h)l[h]==f&&(g=h),l[h]=c(l[h],h);return d.slimbox(l,g,a)})}})(jQuery);
jQuery.extend(jQuery.easing,{easeOutElastic:function(d,b,a,c,e){var f=0,g=c;if(0==b)return a;if(1==(b/=e))return a+c;f||(f=.3*e);g<Math.abs(c)?(g=c,d=f/4):d=f/(2*Math.PI)*Math.asin(c/g);return g*Math.pow(2,-10*b)*Math.sin(2*(b*e-d)*Math.PI/f)+c+a}});/android|iphone|ipod|series60|symbian|windows ce|blackberry/i.test(navigator.userAgent);
jQuery(function(d){d("a[href]").filter(function(){return/.(jpg|png|gif)$/i.test(this.href)}).slimbox({},null,function(b){return this==b||this.parentNode&&this.parentNode==b.parentNode})});!function(d){"function"==typeof define&&define.amd?define(["jquery"],d):"undefined"!=typeof exports?module.exports=d(require("jquery")):d(jQuery)}(function(d){var b=window.Slick||{};b=function(){var a=0;return function(c,b){this.defaults={accessibility:!0,adaptiveHeight:!1,appendArrows:d(c),appendDots:d(c),arrows:!0,asNavFor:null,prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="Previous" tabindex="0" role="button">Previous</button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="Next" tabindex="0" role="button">Next</button>',
autoplay:!1,autoplaySpeed:3E3,centerMode:!1,centerPadding:"50px",cssEase:"ease",customPaging:function(a,c){return d('<button type="button" data-role="none" role="button" tabindex="0" />').text(c+1)},dots:!1,dotsClass:"slick-dots",draggable:!0,easing:"linear",edgeFriction:.35,fade:!1,focusOnSelect:!1,infinite:!0,initialSlide:0,lazyLoad:"ondemand",mobileFirst:!1,pauseOnHover:!0,pauseOnFocus:!0,pauseOnDotsHover:!1,respondTo:"window",responsive:null,rows:1,rtl:!1,slide:"",slidesPerRow:1,slidesToShow:1,
slidesToScroll:1,speed:500,swipe:!0,swipeToSlide:!1,touchMove:!0,touchThreshold:5,useCSS:!0,useTransform:!0,variableWidth:!1,vertical:!1,verticalSwiping:!1,waitForAnimate:!0,zIndex:1E3};this.initials={animating:!1,dragging:!1,autoPlayTimer:null,currentDirection:0,currentLeft:null,currentSlide:0,direction:1,$dots:null,listWidth:null,listHeight:null,loadIndex:0,$nextArrow:null,$prevArrow:null,slideCount:null,slideWidth:null,$slideTrack:null,$slides:null,sliding:!1,slideOffset:0,swipeLeft:null,$list:null,
touchObject:{},transformsEnabled:!1,unslicked:!1};d.extend(this,this.initials);this.animProp=this.animType=this.activeBreakpoint=null;this.breakpoints=[];this.breakpointSettings=[];this.interrupted=this.focussed=this.cssTransitions=!1;this.hidden="hidden";this.paused=!0;this.respondTo=this.positionProp=null;this.rowCount=1;this.shouldClick=!0;this.$slider=d(c);this.transitionType=this.transformType=this.$slidesCache=null;this.visibilityChange="visibilitychange";this.windowWidth=0;this.windowTimer=
null;var e=d(c).data("slick")||{};this.options=d.extend({},this.defaults,b,e);this.currentSlide=this.options.initialSlide;this.originalSettings=this.options;"undefined"!=typeof document.mozHidden?(this.hidden="mozHidden",this.visibilityChange="mozvisibilitychange"):"undefined"!=typeof document.webkitHidden&&(this.hidden="webkitHidden",this.visibilityChange="webkitvisibilitychange");this.autoPlay=d.proxy(this.autoPlay,this);this.autoPlayClear=d.proxy(this.autoPlayClear,this);this.autoPlayIterator=
d.proxy(this.autoPlayIterator,this);this.changeSlide=d.proxy(this.changeSlide,this);this.clickHandler=d.proxy(this.clickHandler,this);this.selectHandler=d.proxy(this.selectHandler,this);this.setPosition=d.proxy(this.setPosition,this);this.swipeHandler=d.proxy(this.swipeHandler,this);this.dragHandler=d.proxy(this.dragHandler,this);this.keyHandler=d.proxy(this.keyHandler,this);this.instanceUid=a++;this.htmlExpr=/^(?:\s*(<[\w\W]+>)[^>]*)$/;this.registerBreakpoints();this.init(!0)}}();b.prototype.activateADA=
function(){this.$slideTrack.find(".slick-active").attr({"aria-hidden":"false"}).find("a, input, button, select").attr({tabindex:"0"})};b.prototype.addSlide=b.prototype.slickAdd=function(a,c,b){if("boolean"==typeof c)b=c,c=null;else if(0>c||c>=this.slideCount)return!1;this.unload();"number"==typeof c?0===c&&0===this.$slides.length?d(a).appendTo(this.$slideTrack):b?d(a).insertBefore(this.$slides.eq(c)):d(a).insertAfter(this.$slides.eq(c)):!0===b?d(a).prependTo(this.$slideTrack):d(a).appendTo(this.$slideTrack);
this.$slides=this.$slideTrack.children(this.options.slide);this.$slideTrack.children(this.options.slide).detach();this.$slideTrack.append(this.$slides);this.$slides.each(function(a,c){d(c).attr("data-slick-index",a)});this.$slidesCache=this.$slides;this.reinit()};b.prototype.animateHeight=function(){if(1===this.options.slidesToShow&&!0===this.options.adaptiveHeight&&!1===this.options.vertical){var a=this.$slides.eq(this.currentSlide).outerHeight(!0);this.$list.animate({height:a},this.options.speed)}};
b.prototype.animateSlide=function(a,c){var b={},f=this;f.animateHeight();!0===f.options.rtl&&!1===f.options.vertical&&(a=-a);!1===f.transformsEnabled?!1===f.options.vertical?f.$slideTrack.animate({left:a},f.options.speed,f.options.easing,c):f.$slideTrack.animate({top:a},f.options.speed,f.options.easing,c):!1===f.cssTransitions?(!0===f.options.rtl&&(f.currentLeft=-f.currentLeft),d({animStart:f.currentLeft}).animate({animStart:a},{duration:f.options.speed,easing:f.options.easing,step:function(a){a=
Math.ceil(a);!1===f.options.vertical?(b[f.animType]="translate("+a+"px, 0px)",f.$slideTrack.css(b)):(b[f.animType]="translate(0px,"+a+"px)",f.$slideTrack.css(b))},complete:function(){c&&c.call()}})):(f.applyTransition(),a=Math.ceil(a),!1===f.options.vertical?b[f.animType]="translate3d("+a+"px, 0px, 0px)":b[f.animType]="translate3d(0px,"+a+"px, 0px)",f.$slideTrack.css(b),c&&setTimeout(function(){f.disableTransition();c.call()},f.options.speed))};b.prototype.getNavTarget=function(){var a=this.options.asNavFor;
return a&&null!==a&&(a=d(a).not(this.$slider)),a};b.prototype.asNavFor=function(a){var c=this.getNavTarget();null!==c&&"object"==typeof c&&c.each(function(){var c=d(this).slick("getSlick");c.unslicked||c.slideHandler(a,!0)})};b.prototype.applyTransition=function(a){var c={};!1===this.options.fade?c[this.transitionType]=this.transformType+" "+this.options.speed+"ms "+this.options.cssEase:c[this.transitionType]="opacity "+this.options.speed+"ms "+this.options.cssEase;!1===this.options.fade?this.$slideTrack.css(c):
this.$slides.eq(a).css(c)};b.prototype.autoPlay=function(){this.autoPlayClear();this.slideCount>this.options.slidesToShow&&(this.autoPlayTimer=setInterval(this.autoPlayIterator,this.options.autoplaySpeed))};b.prototype.autoPlayClear=function(){this.autoPlayTimer&&clearInterval(this.autoPlayTimer)};b.prototype.autoPlayIterator=function(){var a=this.currentSlide+this.options.slidesToScroll;this.paused||this.interrupted||this.focussed||(!1===this.options.infinite&&(1===this.direction&&this.currentSlide+
1===this.slideCount-1?this.direction=0:0===this.direction&&(a=this.currentSlide-this.options.slidesToScroll,0===this.currentSlide-1&&(this.direction=1))),this.slideHandler(a))};b.prototype.buildArrows=function(){!0===this.options.arrows&&(this.$prevArrow=d(this.options.prevArrow).addClass("slick-arrow"),this.$nextArrow=d(this.options.nextArrow).addClass("slick-arrow"),this.slideCount>this.options.slidesToShow?(this.$prevArrow.removeClass("slick-hidden").removeAttr("aria-hidden tabindex"),this.$nextArrow.removeClass("slick-hidden").removeAttr("aria-hidden tabindex"),
this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.prependTo(this.options.appendArrows),this.htmlExpr.test(this.options.nextArrow)&&this.$nextArrow.appendTo(this.options.appendArrows),!0!==this.options.infinite&&this.$prevArrow.addClass("slick-disabled").attr("aria-disabled","true")):this.$prevArrow.add(this.$nextArrow).addClass("slick-hidden").attr({"aria-disabled":"true",tabindex:"-1"}))};b.prototype.buildDots=function(){var a;if(!0===this.options.dots&&this.slideCount>this.options.slidesToShow){this.$slider.addClass("slick-dotted");
var c=d("<ul />").addClass(this.options.dotsClass);for(a=0;a<=this.getDotCount();a+=1)c.append(d("<li />").append(this.options.customPaging.call(this,this,a)));this.$dots=c.appendTo(this.options.appendDots);this.$dots.find("li").first().addClass("slick-active").attr("aria-hidden","false")}};b.prototype.buildOut=function(){this.$slides=this.$slider.children(this.options.slide+":not(.slick-cloned)").addClass("slick-slide");this.slideCount=this.$slides.length;this.$slides.each(function(a,c){d(c).attr("data-slick-index",
a).data("originalStyling",d(c).attr("style")||"")});this.$slider.addClass("slick-slider");this.$slideTrack=0===this.slideCount?d('<div class="slick-track"/>').appendTo(this.$slider):this.$slides.wrapAll('<div class="slick-track"/>').parent();this.$list=this.$slideTrack.wrap('<div aria-live="polite" class="slick-list"/>').parent();this.$slideTrack.css("opacity",0);!0!==this.options.centerMode&&!0!==this.options.swipeToSlide||(this.options.slidesToScroll=1);d("img[data-lazy]",this.$slider).not("[src]").addClass("slick-loading");
this.setupInfinite();this.buildArrows();this.buildDots();this.updateDots();this.setSlideClasses("number"==typeof this.currentSlide?this.currentSlide:0);!0===this.options.draggable&&this.$list.addClass("draggable")};b.prototype.buildRows=function(){var a,c,b,d,g;if(d=document.createDocumentFragment(),g=this.$slider.children(),1<this.options.rows){var k=this.options.slidesPerRow*this.options.rows;var p=Math.ceil(g.length/k);for(a=0;p>a;a++){var l=document.createElement("div");for(c=0;c<this.options.rows;c++){var m=
document.createElement("div");for(b=0;b<this.options.slidesPerRow;b++){var h=a*k+(c*this.options.slidesPerRow+b);g.get(h)&&m.appendChild(g.get(h))}l.appendChild(m)}d.appendChild(l)}this.$slider.empty().append(d);this.$slider.children().children().children().css({width:100/this.options.slidesPerRow+"%",display:"inline-block"})}};b.prototype.checkResponsive=function(a,c){var b,f,g=!1;var k=this.$slider.width();var p=window.innerWidth||d(window).width();if("window"===this.respondTo?f=p:"slider"===this.respondTo?
f=k:"min"===this.respondTo&&(f=Math.min(p,k)),this.options.responsive&&this.options.responsive.length&&null!==this.options.responsive){k=null;for(b in this.breakpoints)this.breakpoints.hasOwnProperty(b)&&(!1===this.originalSettings.mobileFirst?f<this.breakpoints[b]&&(k=this.breakpoints[b]):f>this.breakpoints[b]&&(k=this.breakpoints[b]));null!==k?null!==this.activeBreakpoint?(k!==this.activeBreakpoint||c)&&(this.activeBreakpoint=k,"unslick"===this.breakpointSettings[k]?this.unslick(k):(this.options=
d.extend({},this.originalSettings,this.breakpointSettings[k]),!0===a&&(this.currentSlide=this.options.initialSlide),this.refresh(a)),g=k):(this.activeBreakpoint=k,"unslick"===this.breakpointSettings[k]?this.unslick(k):(this.options=d.extend({},this.originalSettings,this.breakpointSettings[k]),!0===a&&(this.currentSlide=this.options.initialSlide),this.refresh(a)),g=k):null!==this.activeBreakpoint&&(this.activeBreakpoint=null,this.options=this.originalSettings,!0===a&&(this.currentSlide=this.options.initialSlide),
this.refresh(a),g=k);a||!1===g||this.$slider.trigger("breakpoint",[this,g])}};b.prototype.changeSlide=function(a,c){var b,f;var g=d(a.currentTarget);switch(g.is("a")&&a.preventDefault(),g.is("li")||(g=g.closest("li")),f=0!==this.slideCount%this.options.slidesToScroll,b=f?0:(this.slideCount-this.currentSlide)%this.options.slidesToScroll,a.data.message){case "previous":g=0===b?this.options.slidesToScroll:this.options.slidesToShow-b;this.slideCount>this.options.slidesToShow&&this.slideHandler(this.currentSlide-
g,!1,c);break;case "next":g=0===b?this.options.slidesToScroll:b;this.slideCount>this.options.slidesToShow&&this.slideHandler(this.currentSlide+g,!1,c);break;case "index":b=0===a.data.index?0:a.data.index||g.index()*this.options.slidesToScroll,this.slideHandler(this.checkNavigable(b),!1,c),g.children().trigger("focus")}};b.prototype.checkNavigable=function(a){var c,b;if(c=this.getNavigableIndexes(),b=0,a>c[c.length-1])a=c[c.length-1];else for(var d in c){if(a<c[d]){a=b;break}b=c[d]}return a};b.prototype.cleanUpEvents=
function(){this.options.dots&&null!==this.$dots&&d("li",this.$dots).off("click.slick",this.changeSlide).off("mouseenter.slick",d.proxy(this.interrupt,this,!0)).off("mouseleave.slick",d.proxy(this.interrupt,this,!1));this.$slider.off("focus.slick blur.slick");!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow&&this.$prevArrow.off("click.slick",this.changeSlide),this.$nextArrow&&this.$nextArrow.off("click.slick",this.changeSlide));this.$list.off("touchstart.slick mousedown.slick",
this.swipeHandler);this.$list.off("touchmove.slick mousemove.slick",this.swipeHandler);this.$list.off("touchend.slick mouseup.slick",this.swipeHandler);this.$list.off("touchcancel.slick mouseleave.slick",this.swipeHandler);this.$list.off("click.slick",this.clickHandler);d(document).off(this.visibilityChange,this.visibility);this.cleanUpSlideEvents();!0===this.options.accessibility&&this.$list.off("keydown.slick",this.keyHandler);!0===this.options.focusOnSelect&&d(this.$slideTrack).children().off("click.slick",
this.selectHandler);d(window).off("orientationchange.slick.slick-"+this.instanceUid,this.orientationChange);d(window).off("resize.slick.slick-"+this.instanceUid,this.resize);d("[draggable!=true]",this.$slideTrack).off("dragstart",this.preventDefault);d(window).off("load.slick.slick-"+this.instanceUid,this.setPosition);d(document).off("ready.slick.slick-"+this.instanceUid,this.setPosition)};b.prototype.cleanUpSlideEvents=function(){this.$list.off("mouseenter.slick",d.proxy(this.interrupt,this,!0));
this.$list.off("mouseleave.slick",d.proxy(this.interrupt,this,!1))};b.prototype.cleanUpRows=function(){var a;1<this.options.rows&&(a=this.$slides.children().children(),a.removeAttr("style"),this.$slider.empty().append(a))};b.prototype.clickHandler=function(a){!1===this.shouldClick&&(a.stopImmediatePropagation(),a.stopPropagation(),a.preventDefault())};b.prototype.destroy=function(a){this.autoPlayClear();this.touchObject={};this.cleanUpEvents();d(".slick-cloned",this.$slider).detach();this.$dots&&
this.$dots.remove();this.$prevArrow&&this.$prevArrow.length&&(this.$prevArrow.removeClass("slick-disabled slick-arrow slick-hidden").removeAttr("aria-hidden aria-disabled tabindex").css("display",""),this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.remove());this.$nextArrow&&this.$nextArrow.length&&(this.$nextArrow.removeClass("slick-disabled slick-arrow slick-hidden").removeAttr("aria-hidden aria-disabled tabindex").css("display",""),this.htmlExpr.test(this.options.nextArrow)&&this.$nextArrow.remove());
this.$slides&&(this.$slides.removeClass("slick-slide slick-active slick-center slick-visible slick-current").removeAttr("aria-hidden").removeAttr("data-slick-index").each(function(){d(this).attr("style",d(this).data("originalStyling"))}),this.$slideTrack.children(this.options.slide).detach(),this.$slideTrack.detach(),this.$list.detach(),this.$slider.append(this.$slides));this.cleanUpRows();this.$slider.removeClass("slick-slider");this.$slider.removeClass("slick-initialized");this.$slider.removeClass("slick-dotted");
this.unslicked=!0;a||this.$slider.trigger("destroy",[this])};b.prototype.disableTransition=function(a){var c={};c[this.transitionType]="";!1===this.options.fade?this.$slideTrack.css(c):this.$slides.eq(a).css(c)};b.prototype.fadeSlide=function(a,c){var b=this;!1===b.cssTransitions?(b.$slides.eq(a).css({zIndex:b.options.zIndex}),b.$slides.eq(a).animate({opacity:1},b.options.speed,b.options.easing,c)):(b.applyTransition(a),b.$slides.eq(a).css({opacity:1,zIndex:b.options.zIndex}),c&&setTimeout(function(){b.disableTransition(a);
c.call()},b.options.speed))};b.prototype.fadeSlideOut=function(a){!1===this.cssTransitions?this.$slides.eq(a).animate({opacity:0,zIndex:this.options.zIndex-2},this.options.speed,this.options.easing):(this.applyTransition(a),this.$slides.eq(a).css({opacity:0,zIndex:this.options.zIndex-2}))};b.prototype.filterSlides=b.prototype.slickFilter=function(a){null!==a&&(this.$slidesCache=this.$slides,this.unload(),this.$slideTrack.children(this.options.slide).detach(),this.$slidesCache.filter(a).appendTo(this.$slideTrack),
this.reinit())};b.prototype.focusHandler=function(){var a=this;a.$slider.off("focus.slick blur.slick").on("focus.slick blur.slick","*:not(.slick-arrow)",function(c){c.stopImmediatePropagation();var b=d(this);setTimeout(function(){a.options.pauseOnFocus&&(a.focussed=b.is(":focus"),a.autoPlay())},0)})};b.prototype.getCurrent=b.prototype.slickCurrentSlide=function(){return this.currentSlide};b.prototype.getDotCount=function(){var a=0,c=0,b=0;if(!0===this.options.infinite)for(;a<this.slideCount;)++b,
a=c+this.options.slidesToScroll,c+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;else if(!0===this.options.centerMode)b=this.slideCount;else if(this.options.asNavFor)for(;a<this.slideCount;)++b,a=c+this.options.slidesToScroll,c+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;else b=1+Math.ceil((this.slideCount-this.options.slidesToShow)/this.options.slidesToScroll);return b-
1};b.prototype.getLeft=function(a){var c,b,d,g=0;return this.slideOffset=0,b=this.$slides.first().outerHeight(!0),!0===this.options.infinite?(this.slideCount>this.options.slidesToShow&&(this.slideOffset=this.slideWidth*this.options.slidesToShow*-1,g=b*this.options.slidesToShow*-1),0!==this.slideCount%this.options.slidesToScroll&&a+this.options.slidesToScroll>this.slideCount&&this.slideCount>this.options.slidesToShow&&(a>this.slideCount?(this.slideOffset=(this.options.slidesToShow-(a-this.slideCount))*
this.slideWidth*-1,g=(this.options.slidesToShow-(a-this.slideCount))*b*-1):(this.slideOffset=this.slideCount%this.options.slidesToScroll*this.slideWidth*-1,g=this.slideCount%this.options.slidesToScroll*b*-1))):a+this.options.slidesToShow>this.slideCount&&(this.slideOffset=(a+this.options.slidesToShow-this.slideCount)*this.slideWidth,g=(a+this.options.slidesToShow-this.slideCount)*b),this.slideCount<=this.options.slidesToShow&&(this.slideOffset=0,g=0),!0===this.options.centerMode&&!0===this.options.infinite?
this.slideOffset+=this.slideWidth*Math.floor(this.options.slidesToShow/2)-this.slideWidth:!0===this.options.centerMode&&(this.slideOffset=0,this.slideOffset+=this.slideWidth*Math.floor(this.options.slidesToShow/2)),c=!1===this.options.vertical?a*this.slideWidth*-1+this.slideOffset:a*b*-1+g,!0===this.options.variableWidth&&(d=this.slideCount<=this.options.slidesToShow||!1===this.options.infinite?this.$slideTrack.children(".slick-slide").eq(a):this.$slideTrack.children(".slick-slide").eq(a+this.options.slidesToShow),
c=!0===this.options.rtl?d[0]?-1*(this.$slideTrack.width()-d[0].offsetLeft-d.width()):0:d[0]?-1*d[0].offsetLeft:0,!0===this.options.centerMode&&(d=this.slideCount<=this.options.slidesToShow||!1===this.options.infinite?this.$slideTrack.children(".slick-slide").eq(a):this.$slideTrack.children(".slick-slide").eq(a+this.options.slidesToShow+1),c=!0===this.options.rtl?d[0]?-1*(this.$slideTrack.width()-d[0].offsetLeft-d.width()):0:d[0]?-1*d[0].offsetLeft:0,c+=(this.$list.width()-d.outerWidth())/2)),c};b.prototype.getOption=
b.prototype.slickGetOption=function(a){return this.options[a]};b.prototype.getNavigableIndexes=function(){var a,c=0,b=0,d=[];for(!1===this.options.infinite?a=this.slideCount:(c=-1*this.options.slidesToScroll,b=-1*this.options.slidesToScroll,a=2*this.slideCount);a>c;)d.push(c),c=b+this.options.slidesToScroll,b+=this.options.slidesToScroll<=this.options.slidesToShow?this.options.slidesToScroll:this.options.slidesToShow;return d};b.prototype.getSlick=function(){return this};b.prototype.getSlideCount=
function(){var a,b,e=this;return b=!0===e.options.centerMode?e.slideWidth*Math.floor(e.options.slidesToShow/2):0,!0===e.options.swipeToSlide?(e.$slideTrack.find(".slick-slide").each(function(c,g){return g.offsetLeft-b+d(g).outerWidth()/2>-1*e.swipeLeft?(a=g,!1):void 0}),Math.abs(d(a).attr("data-slick-index")-e.currentSlide)||1):e.options.slidesToScroll};b.prototype.goTo=b.prototype.slickGoTo=function(a,b){this.changeSlide({data:{message:"index",index:parseInt(a)}},b)};b.prototype.init=function(a){d(this.$slider).hasClass("slick-initialized")||
(d(this.$slider).addClass("slick-initialized"),this.buildRows(),this.buildOut(),this.setProps(),this.startLoad(),this.loadSlider(),this.initializeEvents(),this.updateArrows(),this.updateDots(),this.checkResponsive(!0),this.focusHandler());a&&this.$slider.trigger("init",[this]);!0===this.options.accessibility&&this.initADA();this.options.autoplay&&(this.paused=!1,this.autoPlay())};b.prototype.initADA=function(){var a=this;a.$slides.add(a.$slideTrack.find(".slick-cloned")).attr({"aria-hidden":"true",
tabindex:"-1"}).find("a, input, button, select").attr({tabindex:"-1"});a.$slideTrack.attr("role","listbox");a.$slides.not(a.$slideTrack.find(".slick-cloned")).each(function(b){d(this).attr({role:"option","aria-describedby":"slick-slide"+a.instanceUid+b})});null!==a.$dots&&a.$dots.attr("role","tablist").find("li").each(function(b){d(this).attr({role:"presentation","aria-selected":"false","aria-controls":"navigation"+a.instanceUid+b,id:"slick-slide"+a.instanceUid+b})}).first().attr("aria-selected",
"true").end().find("button").attr("role","button").end().closest("div").attr("role","toolbar");a.activateADA()};b.prototype.initArrowEvents=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow.off("click.slick").on("click.slick",{message:"previous"},this.changeSlide),this.$nextArrow.off("click.slick").on("click.slick",{message:"next"},this.changeSlide))};b.prototype.initDotEvents=function(){!0===this.options.dots&&this.slideCount>this.options.slidesToShow&&
d("li",this.$dots).on("click.slick",{message:"index"},this.changeSlide);!0===this.options.dots&&!0===this.options.pauseOnDotsHover&&d("li",this.$dots).on("mouseenter.slick",d.proxy(this.interrupt,this,!0)).on("mouseleave.slick",d.proxy(this.interrupt,this,!1))};b.prototype.initSlideEvents=function(){this.options.pauseOnHover&&(this.$list.on("mouseenter.slick",d.proxy(this.interrupt,this,!0)),this.$list.on("mouseleave.slick",d.proxy(this.interrupt,this,!1)))};b.prototype.initializeEvents=function(){this.initArrowEvents();
this.initDotEvents();this.initSlideEvents();this.$list.on("touchstart.slick mousedown.slick",{action:"start"},this.swipeHandler);this.$list.on("touchmove.slick mousemove.slick",{action:"move"},this.swipeHandler);this.$list.on("touchend.slick mouseup.slick",{action:"end"},this.swipeHandler);this.$list.on("touchcancel.slick mouseleave.slick",{action:"end"},this.swipeHandler);this.$list.on("click.slick",this.clickHandler);d(document).on(this.visibilityChange,d.proxy(this.visibility,this));!0===this.options.accessibility&&
this.$list.on("keydown.slick",this.keyHandler);!0===this.options.focusOnSelect&&d(this.$slideTrack).children().on("click.slick",this.selectHandler);d(window).on("orientationchange.slick.slick-"+this.instanceUid,d.proxy(this.orientationChange,this));d(window).on("resize.slick.slick-"+this.instanceUid,d.proxy(this.resize,this));d("[draggable!=true]",this.$slideTrack).on("dragstart",this.preventDefault);d(window).on("load.slick.slick-"+this.instanceUid,this.setPosition);d(document).on("ready.slick.slick-"+
this.instanceUid,this.setPosition)};b.prototype.initUI=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow.show(),this.$nextArrow.show());!0===this.options.dots&&this.slideCount>this.options.slidesToShow&&this.$dots.show()};b.prototype.keyHandler=function(a){a.target.tagName.match("TEXTAREA|INPUT|SELECT")||(37===a.keyCode&&!0===this.options.accessibility?this.changeSlide({data:{message:!0===this.options.rtl?"next":"previous"}}):39===a.keyCode&&!0===this.options.accessibility&&
this.changeSlide({data:{message:!0===this.options.rtl?"previous":"next"}}))};b.prototype.lazyLoad=function(){function a(a){d("img[data-lazy]",a).each(function(){var a=d(this),b=d(this).attr("data-lazy"),c=document.createElement("img");c.onload=function(){a.animate({opacity:0},100,function(){a.attr("src",b).animate({opacity:1},200,function(){a.removeAttr("data-lazy").removeClass("slick-loading")});g.$slider.trigger("lazyLoaded",[g,a,b])})};c.onerror=function(){a.removeAttr("data-lazy").removeClass("slick-loading").addClass("slick-lazyload-error");
g.$slider.trigger("lazyLoadError",[g,a,b])};c.src=b})}var b,e,f,g=this;!0===g.options.centerMode?!0===g.options.infinite?(b=g.currentSlide+(g.options.slidesToShow/2+1),f=b+g.options.slidesToShow+2):(b=Math.max(0,g.currentSlide-(g.options.slidesToShow/2+1)),f=2+(g.options.slidesToShow/2+1)+g.currentSlide):(b=g.options.infinite?g.options.slidesToShow+g.currentSlide:g.currentSlide,f=Math.ceil(b+g.options.slidesToShow),!0===g.options.fade&&(0<b&&b--,f<=g.slideCount&&f++));b=g.$slider.find(".slick-slide").slice(b,
f);a(b);g.slideCount<=g.options.slidesToShow?(e=g.$slider.find(".slick-slide"),a(e)):g.currentSlide>=g.slideCount-g.options.slidesToShow?(e=g.$slider.find(".slick-cloned").slice(0,g.options.slidesToShow),a(e)):0===g.currentSlide&&(e=g.$slider.find(".slick-cloned").slice(-1*g.options.slidesToShow),a(e))};b.prototype.loadSlider=function(){this.setPosition();this.$slideTrack.css({opacity:1});this.$slider.removeClass("slick-loading");this.initUI();"progressive"===this.options.lazyLoad&&this.progressiveLazyLoad()};
b.prototype.next=b.prototype.slickNext=function(){this.changeSlide({data:{message:"next"}})};b.prototype.orientationChange=function(){this.checkResponsive();this.setPosition()};b.prototype.pause=b.prototype.slickPause=function(){this.autoPlayClear();this.paused=!0};b.prototype.play=b.prototype.slickPlay=function(){this.autoPlay();this.options.autoplay=!0;this.interrupted=this.focussed=this.paused=!1};b.prototype.postSlide=function(a){this.unslicked||(this.$slider.trigger("afterChange",[this,a]),this.animating=
!1,this.setPosition(),this.swipeLeft=null,this.options.autoplay&&this.autoPlay(),!0===this.options.accessibility&&this.initADA())};b.prototype.prev=b.prototype.slickPrev=function(){this.changeSlide({data:{message:"previous"}})};b.prototype.preventDefault=function(a){a.preventDefault()};b.prototype.progressiveLazyLoad=function(a){a=a||1;var b,e,f,g=this,k=d("img[data-lazy]",g.$slider);k.length?(b=k.first(),e=b.attr("data-lazy"),f=document.createElement("img"),f.onload=function(){b.attr("src",e).removeAttr("data-lazy").removeClass("slick-loading");
!0===g.options.adaptiveHeight&&g.setPosition();g.$slider.trigger("lazyLoaded",[g,b,e]);g.progressiveLazyLoad()},f.onerror=function(){3>a?setTimeout(function(){g.progressiveLazyLoad(a+1)},500):(b.removeAttr("data-lazy").removeClass("slick-loading").addClass("slick-lazyload-error"),g.$slider.trigger("lazyLoadError",[g,b,e]),g.progressiveLazyLoad())},f.src=e):g.$slider.trigger("allImagesLoaded",[g])};b.prototype.refresh=function(a){var b=this.slideCount-this.options.slidesToShow;!this.options.infinite&&
this.currentSlide>b&&(this.currentSlide=b);this.slideCount<=this.options.slidesToShow&&(this.currentSlide=0);b=this.currentSlide;this.destroy(!0);d.extend(this,this.initials,{currentSlide:b});this.init();a||this.changeSlide({data:{message:"index",index:b}},!1)};b.prototype.registerBreakpoints=function(){var a,b,e,f=this,g=f.options.responsive||null;if("array"===d.type(g)&&g.length){f.respondTo=f.options.respondTo||"window";for(a in g)if(e=f.breakpoints.length-1,b=g[a].breakpoint,g.hasOwnProperty(a)){for(;0<=
e;)f.breakpoints[e]&&f.breakpoints[e]===b&&f.breakpoints.splice(e,1),e--;f.breakpoints.push(b);f.breakpointSettings[b]=g[a].settings}f.breakpoints.sort(function(a,b){return f.options.mobileFirst?a-b:b-a})}};b.prototype.reinit=function(){this.$slides=this.$slideTrack.children(this.options.slide).addClass("slick-slide");this.slideCount=this.$slides.length;this.currentSlide>=this.slideCount&&0!==this.currentSlide&&(this.currentSlide-=this.options.slidesToScroll);this.slideCount<=this.options.slidesToShow&&
(this.currentSlide=0);this.registerBreakpoints();this.setProps();this.setupInfinite();this.buildArrows();this.updateArrows();this.initArrowEvents();this.buildDots();this.updateDots();this.initDotEvents();this.cleanUpSlideEvents();this.initSlideEvents();this.checkResponsive(!1,!0);!0===this.options.focusOnSelect&&d(this.$slideTrack).children().on("click.slick",this.selectHandler);this.setSlideClasses("number"==typeof this.currentSlide?this.currentSlide:0);this.setPosition();this.focusHandler();this.paused=
!this.options.autoplay;this.autoPlay();this.$slider.trigger("reInit",[this])};b.prototype.resize=function(){var a=this;d(window).width()!==a.windowWidth&&(clearTimeout(a.windowDelay),a.windowDelay=window.setTimeout(function(){a.windowWidth=d(window).width();a.checkResponsive();a.unslicked||a.setPosition()},50))};b.prototype.removeSlide=b.prototype.slickRemove=function(a,b,d){return"boolean"==typeof a?(b=a,a=!0===b?0:this.slideCount-1):a=!0===b?--a:a,1>this.slideCount||0>a||a>this.slideCount-1?!1:
(this.unload(),!0===d?this.$slideTrack.children().remove():this.$slideTrack.children(this.options.slide).eq(a).remove(),this.$slides=this.$slideTrack.children(this.options.slide),this.$slideTrack.children(this.options.slide).detach(),this.$slideTrack.append(this.$slides),this.$slidesCache=this.$slides,void this.reinit())};b.prototype.setCSS=function(a){var b={};!0===this.options.rtl&&(a=-a);var d="left"==this.positionProp?Math.ceil(a)+"px":"0px";var f="top"==this.positionProp?Math.ceil(a)+"px":"0px";
b[this.positionProp]=a;!1===this.transformsEnabled?this.$slideTrack.css(b):(b={},!1===this.cssTransitions?(b[this.animType]="translate("+d+", "+f+")",this.$slideTrack.css(b)):(b[this.animType]="translate3d("+d+", "+f+", 0px)",this.$slideTrack.css(b)))};b.prototype.setDimensions=function(){!1===this.options.vertical?!0===this.options.centerMode&&this.$list.css({padding:"0px "+this.options.centerPadding}):(this.$list.height(this.$slides.first().outerHeight(!0)*this.options.slidesToShow),!0===this.options.centerMode&&
this.$list.css({padding:this.options.centerPadding+" 0px"}));this.listWidth=this.$list.width();this.listHeight=this.$list.height();!1===this.options.vertical&&!1===this.options.variableWidth?(this.slideWidth=Math.ceil(this.listWidth/this.options.slidesToShow),this.$slideTrack.width(Math.ceil(this.slideWidth*this.$slideTrack.children(".slick-slide").length))):!0===this.options.variableWidth?this.$slideTrack.width(5E3*this.slideCount):(this.slideWidth=Math.ceil(this.listWidth),this.$slideTrack.height(Math.ceil(this.$slides.first().outerHeight(!0)*
this.$slideTrack.children(".slick-slide").length)));var a=this.$slides.first().outerWidth(!0)-this.$slides.first().width();!1===this.options.variableWidth&&this.$slideTrack.children(".slick-slide").width(this.slideWidth-a)};b.prototype.setFade=function(){var a,b=this;b.$slides.each(function(c,f){a=b.slideWidth*c*-1;!0===b.options.rtl?d(f).css({position:"relative",right:a,top:0,zIndex:b.options.zIndex-2,opacity:0}):d(f).css({position:"relative",left:a,top:0,zIndex:b.options.zIndex-2,opacity:0})});
b.$slides.eq(b.currentSlide).css({zIndex:b.options.zIndex-1,opacity:1})};b.prototype.setHeight=function(){if(1===this.options.slidesToShow&&!0===this.options.adaptiveHeight&&!1===this.options.vertical){var a=this.$slides.eq(this.currentSlide).outerHeight(!0);this.$list.css("height",a)}};b.prototype.setOption=b.prototype.slickSetOption=function(a,b,e){var c,g,k,p,l=this,m=!1;if("object"===d.type(a)?(g=a,m=b,p="multiple"):"string"===d.type(a)&&(g=a,k=b,m=e,"responsive"===a&&"array"===d.type(b)?p="responsive":
"undefined"!=typeof b&&(p="single")),"single"===p)l.options[g]=k;else if("multiple"===p)d.each(g,function(a,b){l.options[a]=b});else if("responsive"===p)for(c in k)if("array"!==d.type(l.options.responsive))l.options.responsive=[k[c]];else{for(a=l.options.responsive.length-1;0<=a;)l.options.responsive[a].breakpoint===k[c].breakpoint&&l.options.responsive.splice(a,1),a--;l.options.responsive.push(k[c])}m&&(l.unload(),l.reinit())};b.prototype.setPosition=function(){this.setDimensions();this.setHeight();
!1===this.options.fade?this.setCSS(this.getLeft(this.currentSlide)):this.setFade();this.$slider.trigger("setPosition",[this])};b.prototype.setProps=function(){var a=document.body.style;this.positionProp=!0===this.options.vertical?"top":"left";"top"===this.positionProp?this.$slider.addClass("slick-vertical"):this.$slider.removeClass("slick-vertical");void 0===a.WebkitTransition&&void 0===a.MozTransition&&void 0===a.msTransition||!0!==this.options.useCSS||(this.cssTransitions=!0);this.options.fade&&
("number"==typeof this.options.zIndex?3>this.options.zIndex&&(this.options.zIndex=3):this.options.zIndex=this.defaults.zIndex);void 0!==a.OTransform&&(this.animType="OTransform",this.transformType="-o-transform",this.transitionType="OTransition",void 0===a.perspectiveProperty&&void 0===a.webkitPerspective&&(this.animType=!1));void 0!==a.MozTransform&&(this.animType="MozTransform",this.transformType="-moz-transform",this.transitionType="MozTransition",void 0===a.perspectiveProperty&&void 0===a.MozPerspective&&
(this.animType=!1));void 0!==a.webkitTransform&&(this.animType="webkitTransform",this.transformType="-webkit-transform",this.transitionType="webkitTransition",void 0===a.perspectiveProperty&&void 0===a.webkitPerspective&&(this.animType=!1));void 0!==a.msTransform&&(this.animType="msTransform",this.transformType="-ms-transform",this.transitionType="msTransition",void 0===a.msTransform&&(this.animType=!1));void 0!==a.transform&&!1!==this.animType&&(this.animType="transform",this.transformType="transform",
this.transitionType="transition");this.transformsEnabled=this.options.useTransform&&null!==this.animType&&!1!==this.animType};b.prototype.setSlideClasses=function(a){var b,d,f;var g=this.$slider.find(".slick-slide").removeClass("slick-active slick-center slick-current").attr("aria-hidden","true");this.$slides.eq(a).addClass("slick-current");!0===this.options.centerMode?(b=Math.floor(this.options.slidesToShow/2),!0===this.options.infinite&&(a>=b&&a<=this.slideCount-1-b?this.$slides.slice(a-b,a+b+1).addClass("slick-active").attr("aria-hidden",
"false"):(d=this.options.slidesToShow+a,g.slice(d-b+1,d+b+2).addClass("slick-active").attr("aria-hidden","false")),0===a?g.eq(g.length-1-this.options.slidesToShow).addClass("slick-center"):a===this.slideCount-1&&g.eq(this.options.slidesToShow).addClass("slick-center")),this.$slides.eq(a).addClass("slick-center")):0<=a&&a<=this.slideCount-this.options.slidesToShow?this.$slides.slice(a,a+this.options.slidesToShow).addClass("slick-active").attr("aria-hidden","false"):g.length<=this.options.slidesToShow?
g.addClass("slick-active").attr("aria-hidden","false"):(f=this.slideCount%this.options.slidesToShow,d=!0===this.options.infinite?this.options.slidesToShow+a:a,this.options.slidesToShow==this.options.slidesToScroll&&this.slideCount-a<this.options.slidesToShow?g.slice(d-(this.options.slidesToShow-f),d+f).addClass("slick-active").attr("aria-hidden","false"):g.slice(d,d+this.options.slidesToShow).addClass("slick-active").attr("aria-hidden","false"));"ondemand"===this.options.lazyLoad&&this.lazyLoad()};
b.prototype.setupInfinite=function(){var a,b;if(!0===this.options.fade&&(this.options.centerMode=!1),!0===this.options.infinite&&!1===this.options.fade&&(b=null,this.slideCount>this.options.slidesToShow)){var e=!0===this.options.centerMode?this.options.slidesToShow+1:this.options.slidesToShow;for(a=this.slideCount;a>this.slideCount-e;--a)b=a-1,d(this.$slides[b]).clone(!0).attr("id","").attr("data-slick-index",b-this.slideCount).prependTo(this.$slideTrack).addClass("slick-cloned");for(a=0;e>a;a+=1)b=
a,d(this.$slides[b]).clone(!0).attr("id","").attr("data-slick-index",b+this.slideCount).appendTo(this.$slideTrack).addClass("slick-cloned");this.$slideTrack.find(".slick-cloned").find("[id]").each(function(){d(this).attr("id","")})}};b.prototype.interrupt=function(a){a||this.autoPlay();this.interrupted=a};b.prototype.selectHandler=function(a){a=d(a.target).is(".slick-slide")?d(a.target):d(a.target).parents(".slick-slide");a=parseInt(a.attr("data-slick-index"));return a||(a=0),this.slideCount<=this.options.slidesToShow?
(this.setSlideClasses(a),void this.asNavFor(a)):void this.slideHandler(a)};b.prototype.slideHandler=function(a,b,d){var c,e,k,p,l,m=null,h=this;return b=b||!1,!0===h.animating&&!0===h.options.waitForAnimate||!0===h.options.fade&&h.currentSlide===a||h.slideCount<=h.options.slidesToShow?void 0:(!1===b&&h.asNavFor(a),c=a,m=h.getLeft(c),p=h.getLeft(h.currentSlide),h.currentLeft=null===h.swipeLeft?p:h.swipeLeft,!1===h.options.infinite&&!1===h.options.centerMode&&(0>a||a>h.getDotCount()*h.options.slidesToScroll)?
void(!1===h.options.fade&&(c=h.currentSlide,!0!==d?h.animateSlide(p,function(){h.postSlide(c)}):h.postSlide(c))):!1===h.options.infinite&&!0===h.options.centerMode&&(0>a||a>h.slideCount-h.options.slidesToScroll)?void(!1===h.options.fade&&(c=h.currentSlide,!0!==d?h.animateSlide(p,function(){h.postSlide(c)}):h.postSlide(c))):(h.options.autoplay&&clearInterval(h.autoPlayTimer),e=0>c?0!==h.slideCount%h.options.slidesToScroll?h.slideCount-h.slideCount%h.options.slidesToScroll:h.slideCount+c:c>=h.slideCount?
0!==h.slideCount%h.options.slidesToScroll?0:c-h.slideCount:c,h.animating=!0,h.$slider.trigger("beforeChange",[h,h.currentSlide,e]),k=h.currentSlide,h.currentSlide=e,h.setSlideClasses(h.currentSlide),h.options.asNavFor&&(l=h.getNavTarget(),l=l.slick("getSlick"),l.slideCount<=l.options.slidesToShow&&l.setSlideClasses(h.currentSlide)),h.updateDots(),h.updateArrows(),!0===h.options.fade?(!0!==d?(h.fadeSlideOut(k),h.fadeSlide(e,function(){h.postSlide(e)})):h.postSlide(e),void h.animateHeight()):void(!0!==
d?h.animateSlide(m,function(){h.postSlide(e)}):h.postSlide(e))))};b.prototype.startLoad=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&(this.$prevArrow.hide(),this.$nextArrow.hide());!0===this.options.dots&&this.slideCount>this.options.slidesToShow&&this.$dots.hide();this.$slider.addClass("slick-loading")};b.prototype.swipeDirection=function(){var a,b,d,f;return a=this.touchObject.startX-this.touchObject.curX,b=this.touchObject.startY-this.touchObject.curY,d=Math.atan2(b,
a),f=Math.round(180*d/Math.PI),0>f&&(f=360-Math.abs(f)),45>=f&&0<=f?!1===this.options.rtl?"left":"right":360>=f&&315<=f?!1===this.options.rtl?"left":"right":135<=f&&225>=f?!1===this.options.rtl?"right":"left":!0===this.options.verticalSwiping?35<=f&&135>=f?"down":"up":"vertical"};b.prototype.swipeEnd=function(a){if(this.dragging=!1,this.interrupted=!1,this.shouldClick=10<this.touchObject.swipeLength?!1:!0,void 0===this.touchObject.curX)return!1;if(!0===this.touchObject.edgeHit&&this.$slider.trigger("edge",
[this,this.swipeDirection()]),this.touchObject.swipeLength>=this.touchObject.minSwipe){switch(a=this.swipeDirection()){case "left":case "down":var b=this.options.swipeToSlide?this.checkNavigable(this.currentSlide+this.getSlideCount()):this.currentSlide+this.getSlideCount();this.currentDirection=0;break;case "right":case "up":b=this.options.swipeToSlide?this.checkNavigable(this.currentSlide-this.getSlideCount()):this.currentSlide-this.getSlideCount(),this.currentDirection=1}"vertical"!=a&&(this.slideHandler(b),
this.touchObject={},this.$slider.trigger("swipe",[this,a]))}else this.touchObject.startX!==this.touchObject.curX&&(this.slideHandler(this.currentSlide),this.touchObject={})};b.prototype.swipeHandler=function(a){if(!(!1===this.options.swipe||"ontouchend"in document&&!1===this.options.swipe||!1===this.options.draggable&&-1!==a.type.indexOf("mouse")))switch(this.touchObject.fingerCount=a.originalEvent&&void 0!==a.originalEvent.touches?a.originalEvent.touches.length:1,this.touchObject.minSwipe=this.listWidth/
this.options.touchThreshold,!0===this.options.verticalSwiping&&(this.touchObject.minSwipe=this.listHeight/this.options.touchThreshold),a.data.action){case "start":this.swipeStart(a);break;case "move":this.swipeMove(a);break;case "end":this.swipeEnd(a)}};b.prototype.swipeMove=function(a){var b,d,f,g,k;return k=void 0!==a.originalEvent?a.originalEvent.touches:null,!this.dragging||k&&1!==k.length?!1:(b=this.getLeft(this.currentSlide),this.touchObject.curX=void 0!==k?k[0].pageX:a.clientX,this.touchObject.curY=
void 0!==k?k[0].pageY:a.clientY,this.touchObject.swipeLength=Math.round(Math.sqrt(Math.pow(this.touchObject.curX-this.touchObject.startX,2))),!0===this.options.verticalSwiping&&(this.touchObject.swipeLength=Math.round(Math.sqrt(Math.pow(this.touchObject.curY-this.touchObject.startY,2)))),d=this.swipeDirection(),"vertical"!==d?(void 0!==a.originalEvent&&4<this.touchObject.swipeLength&&a.preventDefault(),g=(!1===this.options.rtl?1:-1)*(this.touchObject.curX>this.touchObject.startX?1:-1),!0===this.options.verticalSwiping&&
(g=this.touchObject.curY>this.touchObject.startY?1:-1),f=this.touchObject.swipeLength,this.touchObject.edgeHit=!1,!1===this.options.infinite&&(0===this.currentSlide&&"right"===d||this.currentSlide>=this.getDotCount()&&"left"===d)&&(f=this.touchObject.swipeLength*this.options.edgeFriction,this.touchObject.edgeHit=!0),!1===this.options.vertical?this.swipeLeft=b+f*g:this.swipeLeft=b+f*(this.$list.height()/this.listWidth)*g,!0===this.options.verticalSwiping&&(this.swipeLeft=b+f*g),!0===this.options.fade||
!1===this.options.touchMove?!1:!0===this.animating?(this.swipeLeft=null,!1):void this.setCSS(this.swipeLeft)):void 0)};b.prototype.swipeStart=function(a){var b;return this.interrupted=!0,1!==this.touchObject.fingerCount||this.slideCount<=this.options.slidesToShow?(this.touchObject={},!1):(void 0!==a.originalEvent&&void 0!==a.originalEvent.touches&&(b=a.originalEvent.touches[0]),this.touchObject.startX=this.touchObject.curX=void 0!==b?b.pageX:a.clientX,this.touchObject.startY=this.touchObject.curY=
void 0!==b?b.pageY:a.clientY,void(this.dragging=!0))};b.prototype.unfilterSlides=b.prototype.slickUnfilter=function(){null!==this.$slidesCache&&(this.unload(),this.$slideTrack.children(this.options.slide).detach(),this.$slidesCache.appendTo(this.$slideTrack),this.reinit())};b.prototype.unload=function(){d(".slick-cloned",this.$slider).remove();this.$dots&&this.$dots.remove();this.$prevArrow&&this.htmlExpr.test(this.options.prevArrow)&&this.$prevArrow.remove();this.$nextArrow&&this.htmlExpr.test(this.options.nextArrow)&&
this.$nextArrow.remove();this.$slides.removeClass("slick-slide slick-active slick-visible slick-current").attr("aria-hidden","true").css("width","")};b.prototype.unslick=function(a){this.$slider.trigger("unslick",[this,a]);this.destroy()};b.prototype.updateArrows=function(){!0===this.options.arrows&&this.slideCount>this.options.slidesToShow&&!this.options.infinite&&(this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false"),this.$nextArrow.removeClass("slick-disabled").attr("aria-disabled",
"false"),0===this.currentSlide?(this.$prevArrow.addClass("slick-disabled").attr("aria-disabled","true"),this.$nextArrow.removeClass("slick-disabled").attr("aria-disabled","false")):this.currentSlide>=this.slideCount-this.options.slidesToShow&&!1===this.options.centerMode?(this.$nextArrow.addClass("slick-disabled").attr("aria-disabled","true"),this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false")):this.currentSlide>=this.slideCount-1&&!0===this.options.centerMode&&(this.$nextArrow.addClass("slick-disabled").attr("aria-disabled",
"true"),this.$prevArrow.removeClass("slick-disabled").attr("aria-disabled","false")))};b.prototype.updateDots=function(){null!==this.$dots&&(this.$dots.find("li").removeClass("slick-active").attr("aria-hidden","true"),this.$dots.find("li").eq(Math.floor(this.currentSlide/this.options.slidesToScroll)).addClass("slick-active").attr("aria-hidden","false"))};b.prototype.visibility=function(){this.options.autoplay&&(document[this.hidden]?this.interrupted=!0:this.interrupted=!1)};d.fn.slick=function(){var a,
c,d=arguments[0],f=Array.prototype.slice.call(arguments,1),g=this.length;for(a=0;g>a;a++)if("object"==typeof d||"undefined"==typeof d?this[a].slick=new b(this[a],d):c=this[a].slick[d].apply(this[a].slick,f),"undefined"!=typeof c)return c;return this}});
$(document).ready(function(){$(".slider-nav").slick({lazyLoad:"ondemand",dots:!1,infinite:!0,speed:300,slidesToShow:4,slidesToScroll:1,autoplay:!0,autoplaySpeed:2E3,responsive:[{breakpoint:1024,settings:{slidesToShow:3,slidesToScroll:3,infinite:!0,dots:!0}},{breakpoint:600,settings:{slidesToShow:2,slidesToScroll:2}},{breakpoint:480,settings:{slidesToShow:1,slidesToScroll:1}}]})});
//]]>